### ISSUE TITLE
Bug report: drying_target channel is empty

### ISSUE THREAD

**Issue by sirupflex** [BjoernLange/openhab-miele-cloud-binding-beta#4] opened 2020-09-19 11:19 UTC
# Expected Behavior
When turning on the tumble dryer and selecting a program (not yet starting the program), I expect to see the selected program name in the program_active channel. I assume I would also see something for the "drying target" (although I have no clue what it should be) in the drying_target channel.

# Actual Behavior
When turning on the tumble dryer and selecting a program (not yet starting the program), I do not see the program name in the program_active channel for any of the programs, i.e. no matter which program I select. Also, when starting the program, it is still not displayed in the program_active channel. Other data like elapsed time, program_progress, etc. is available. When running a program, however, the channel drying_target remains empty (I guess there should be some info in it).

# Environment
Binding version: v1.0.0-beta.1
openHAB version: 2.5.6
Running on: docker (QNAP Container Station)
Involved Miele devices: Tumble Dryer TWR800-60

# Steps to Reproduce
1. Create a sitemap displaying the channel program_active for the connected tumble dryer
2. Turn on the tumble dryer and select any program (no name is reflected in the program_active channel)

# Possible Solution
n/a

# Additional information
n/a

**Comment by BjoernLange** [comment] 2020-09-20 05:52
Thank you for your report!

This issue might be related to the Miele 3rd party cloud service. Please follow the steps that I outlined [here](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta/issues/3#issuecomment-695748822) for your tumble dryer and post the output of the command.

**Comment by sirupflex** [comment] 2020-09-20 09:33
Hi Bjoern,
I turned on the tumble dryer, selected a program and ran the command as instructed. This is the output:

{"ProgramID":{"value_raw":2,"value_localized":"","key_localized":"Program Id"},"status":{"value_raw":3,"value_localized":"Program selected","key_localized":"State"},"programType":{"value_raw":3,"value_localized":"Cleaning-/ Care program","key_localized":"Program type"},"programPhase":{"value_raw":512,"value_localized":"","key_localized":"Phase"},"remainingTime":[1,17],"startTime":[0,0],"targetTemperature":[{"value_raw":-32768,"value_localized":null,"unit":"Celsius"},{"value_raw":-32768,"value_localized":null,"unit":"Celsius"},{"value_raw":-32768,"value_localized":null,"unit":"Celsius"}],"temperature":[{"value_raw":-32768,"value_localized":null,"unit":"Celsius"},{"value_raw":-32768,"value_localized":null,"unit":"Celsius"},{"value_raw":-32768,"value_localized":null,"unit":"Celsius"}],"signalInfo":false,"signalFailure":false,"signalDoor":true,"remoteEnable":{"fullRemoteControl":true,"smartGrid":false,"mobileStart":false},"light":0,"elapsedTime":[0,0],"spinningSpeed":{"unit":"rpm","value_raw":null,"value_localized":null,"key_localized":"Spinning Speed"},"dryingStep":{"value_raw":2,"value_localized":"Normal","key_localized":"Drying level"},"ventilationStep":{"value_raw":null,"value_localized":"","key_localized":"Power Level"},"plateStep":[]}

**Comment by BjoernLange** [comment] 2020-09-21 11:13
Thank you for providing the output @sirupflex. The empty program_active channel has the same root cause as in #3.
The `drying_target` channel should not be empty according to the output:
```json
"dryingStep": {
    "value_raw": 2,
    "value_localized": "Normal", # Value is present here
    "key_localized": "Drying level"
}
```
This needs to be checked.

**Comment by BjoernLange** [comment] 2020-11-12 06:23
Confirmed, affects multiple users (see [forum](https://community.openhab.org/t/miele-cloud-binding/93266/60?u=bjoernlange)).

The device involved is a washer-dryer WTH730.

**Comment by BjoernLange** [comment] 2020-11-17 08:18
Hi @sirupflex, I tested the `drying_target` channel today with a TCJ680WP dryer and it works fine. I used the `beta.2` binding. Have you already migrated to this version?

I tried both, pairing via assistant and `.things` and `.items` files. Could you check whether there is some problem with your configuration? Just for reference, here is the configuration I tested with:
`miele.things`
```
Bridge mielecloud:account:itemis [ accessToken="<my access token>", locale="en" ] {
    Thing dryer 000140512345 "Clothes Dryer TCJ680WP" [ ]
}
```
`miele.items`
```
String Drying_Target "DryingTarget" {channel="mielecloud:dryer:itemis:000140512345:drying_target"}
```

If your configuration is fine, could you check whether something appears in the logs regarding the item linked to the `drying_target` channel? When creating the item there should be a message like
```
2020-11-17 09:08:52.925 [.ItemChannelLinkAddedEvent] - Link 'Drying_Target-mielecloud:dryer:itemis:000140512345:drying_target' has been added.
```
followed by something like
```
2020-11-17 09:09:21.027 [vent.ItemStateChangedEvent] - Drying_Target changed from UNDEF to Smoothing
```
when the device is turned on and a program is selected.

**Comment by sirupflex** [comment] 2020-11-20 09:42
Hi @BjoernLange , I installed beta2 and I do have the drying_target data now. My item definition was on "Number" and not "String", which was the root cause it seems. Not sure if the beta1 documentation had an error or if the mistake was on my side. The current documentation does show the correct "String" type.

I still do not see the program_active data for the dryer, same as issue #3 reported for the dishwasher. Shall I open another issue for this or is #3 covering all devices for this channel?

**Comment by BjoernLange** [comment] 2020-11-20 13:49
Thank you for checking on this! I will close this issue now as it seems that the problem has been resolved. #3 covers the `program_active` channel, there is no need for another issue.

**Closed as completed by BjoernLange** 2020-11-20 13:49 UTC
Labels: bug, confirmed
