### ISSUE TITLE
Bug report: Program name missing or wrong

### ISSUE THREAD

**Issue by sn0west** [BjoernLange/openhab-miele-cloud-binding-beta#7] opened 2020-09-19 19:07 UTC
# Expected Behavior

QuickPowerWash, SolarWash and Automatic in active program list.

# Actual Behavior

QuickPowerWash, SolarWash and Automatic is not in the active program list.
SolarWash is recognised as Automatic  active program.

# Environment

- Binding version: v1.0.0-beta.1
- openHAB version: openHAB 2.5.8
- Running on: docker
- Involved Miele devices: Dishwaser G7365

# Steps to Reproduce

Changing the active programm (QuickPowerWash) on the dishwasher do change the active program in openhab binding to "-"
Choosing solarwash on the dishwasher change it into Automatic in openhab
changing the programm to automatic on the dishwaser change the active program in open hab to "-"

# Possible Solution

enhance the program list ansd check the id's maybe ?

**Comment by BjoernLange** [comment] 2020-09-20 06:01
Thank you for your report!

This issue might be related to the Miele 3rd party cloud service. Please follow the steps that I outlined [here](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta/issues/3#issuecomment-695748822) and post the output of the command. As you use docker I assume you are familiar with the linux terminal.

**Comment by BjoernLange** [comment] 2020-09-21 11:25
This is the same localization problem as in #3. Further tracking is done there.

**Comment by BjoernLange** [comment] 2020-09-21 11:25
Duplicate of #3

**Closed as completed** 2020-09-21 11:26 UTC
Labels: bug, confirmed, cloud issue
